
apiVersion: apps/v1
kind: Deployment
metadata:
 name: Myprivate-deploy
spec:
 replicas: 2
 template:
  metadata:
   name: myappspod
   labels:
    app: myprivateapp
  spec:
   containers:
    - name: myapp-container
      image: stacksimplify/kubenginx:3.0.0
      ports:
       containerPort: 80

 selector:
  matchLabels:
   app: myprivateapp